# Generated by Django 4.1.7 on 2023-04-02 18:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0005_participant_alter_meetup_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetup',
            name='date',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meetup',
            name='organizor_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='meetup',
            name='participaants',
            field=models.ManyToManyField(blank=True, null=True, to='meetups.participant'),
        ),
    ]
