# Generated by Django 4.1.7 on 2023-04-02 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0006_meetup_date_meetup_organizor_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetup',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='meetup',
            name='organizor_email',
            field=models.EmailField(max_length=254),
        ),
    ]
