# Generated by Django 4.1.7 on 2023-04-02 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0007_alter_meetup_date_alter_meetup_organizor_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetup',
            name='participaants',
        ),
        migrations.AddField(
            model_name='meetup',
            name='participants',
            field=models.ManyToManyField(blank=True, to='meetups.participant'),
        ),
    ]
